# Vetores no numpy
Alguns comportamentos durante as manipulações podem parecer estranhos. Isso pode ocorrer devido a estrutura de dados que estamos utilizando nessas manipulações. A seguir veja um exemplo entre uma matriz de ordem 1 e um vetor coluna.

In [4]:
import numpy as np

# Cria cinco variáveis gaussianas aleatórias
a = np.random.randn(5)
print(a)
# Pelo shape, podemos ver que é uma estrutura de cinco colunas
print(a.shape)

[ 1.00405494  0.04095235  0.32742944 -1.29322123  0.8797873 ]
(5,)


Acaba que isso se torna uma matriz de ordem 1, não um vetor linha nem um vetor coluna. Isso causa efeitos não desejáveis, por exemplo:
- A sua transposta ser igual a matriz original;
- O seu produto externo não resultar em uma matriz, mas em um número.

In [6]:
print(a.T)
print(np.dot(a, a.T))

[ 1.00405494  0.04095235  0.32742944 -1.29322123  0.8797873 ]
3.5634602985023056


Ao invés de usar essas estruturas de matriz de ordem 1, podemos utilizar, por exemplo, um vetor coluna (5, 1).

In [7]:
a = np.random.randn(5, 1)
print(a)

[[ 0.71673429]
 [ 1.60794391]
 [ 0.54658164]
 [ 1.50521085]
 [-0.66886241]]


Dessa forma, sua transposta será um vetor linha (1, 5).

In [8]:
print(a.T)

[[ 0.71673429  1.60794391  0.54658164  1.50521085 -0.66886241]]


E o seu produto externo será uma matriz, assim como esperamos que seja.

In [9]:
print(np.dot(a, a.T))

[[ 0.51370805  1.15246854  0.3917538   1.07883623 -0.47939663]
 [ 1.15246854  2.58548363  0.87887262  2.42029462 -1.07549325]
 [ 0.3917538   0.87887262  0.29875149  0.82272061 -0.36558791]
 [ 1.07883623  2.42029462  0.82272061  2.26565969 -1.00677896]
 [-0.47939663 -1.07549325 -0.36558791 -1.00677896  0.44737693]]
